language: ruby

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.6"

cache:
  directories:
    - vendor/bundle

rvm: "2.5.1"

env:
  - RAILS_ENV=test

before_script:
  - cp config/database.yml.travis config/database.yml
