language: ruby

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.3"

cache:
  directories:
    - vendor/bundle

rvm: "2.3.1"

env:
  - DATABASE_NAME=travis_ci_test

before_install:
  - gem install bundler -v 1.12.4

install:
  - bundle _1.12.4_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - psql -c 'create database main;' -U postgres
  - psql -c 'create database logs;' -U postgres
