language: ruby

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.6"

cache:
  directories:
    - vendor/bundle

rvm: "2.3.4"

env:
  - RAILS_ENV=test

script:
  - bundle exec rspec spec
  - script/validate_structure_file.rb
  - cat db/main/structure.sql| grep "AS integer"

before_script:
  - cp config/database.yml.travis config/database.yml
