language: ruby

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.3"

cache:
  directories:
    - vendor/bundle

rvm: "2.3.1"

env:
  - RAILS_ENV=test
  - RAILS_ENV=test_logs

matrix:
  fast_finish: true

before_install:
  - gem install bundler -v 1.13.6

install:
  - bundle _1.12.4_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - cp config/database.yml.travis config/database.yml
