language: ruby

sudo: false

services:
  - postgresql

addons:
  postgresql: "9.3"

cache:
  directories:
    - vendor/bundle

rvm:
  - "2.0"
  - "2.1"
  - "2.2"

matrix:
  fast_finish: true

before_install:
  - gem install bundler -v 1.12.4

install:
  - bundle _1.12.4_ install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - 'cp config/database.yml.travis config/database.yml'
  - 'RAILS_ENV=test bundle exec rake db:create --trace'
  - 'RAILS_ENV=test bundle exec rake db:migrate'
