# This is only used for standalone_migrations. In other contexts
# Travis.config.database will be used.

defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning
  username: <%= ENV['USER'] %>
  host: <%= ENV.fetch('PGHOST', 'localhost') %>

development:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'travis_development') %>

test:
  <<: *defaults
  database: <%= ENV.fetch('DATABASE_NAME', 'travis_test') %>
